# Generated by Django 4.2 on 2023-05-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_category_subcategory_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
